### ISSUE TITLE
React Upgrade: Cancel button in Question Library is not working

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#149]
_Instructions are in italics and can be deleted_
- _Give the issue a descriptive title_
- _Add a label: bug | change | story_
- _Pick the appropriate content template below:_ 

_For a CHANGE or STORY include these headings:_

### Acceptance Criteria

_For a BUG include these headings:_

**Describe the bug**
React Upgrade: Cancel button in Question Library is not working. 
1. Load Question Library, select a section (Eg. 2.2, 2.3) and hit show questions
2. Once the questions are displayed hit Add more sections
3. The sections that were selected previously (2.2, 2.3) are deselected already.

In production the previously selected sections are retained and Cancel button is used to deselect the existing selections. But in staging the Cancel button is not doing anything in this scenario

https://drive.google.com/file/d/1VgGWzflgASAiUUI7qTkflYrZ7eWLRx4U/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathanstitt** [comment]
fixed by https://github.com/openstax/tutor-js/pull/2445

**Comment by Malar-Natarajan** [comment]
Issue mentioned in the description still exists. Please refer the issue description & video for details

**Comment by nathanstitt** [comment]
the cancel button only clears the selections, we should rename the cancel to be "clear" and  add a "back" button . I'll open a change req
