### ISSUE TITLE
Welcome to tutor pop up triggers briefly when a new teacher account is created 

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#574]
### Description
When a new verified teacher logs into tutor for the first time they will get the welcome to tutor pop up briefly and not be able to click on it. Once they complete the new course tour and navigate back to the course dashboard, they get the welcome to tutor pop up again and can click on it the second time. 

**To Reproduce**
Steps to reproduce the behavior are
1. Create a new teacher account in tutor
2. Log out and get the account verified as an instructor
3. Log back into tutor with the newly verified teacher account
4. Notice that the welcome to tutor pop up shows briefly after a new teacher log in
5. Going through the tour of a new course and then navigating back to the course menu will trigger the welcome to tutor pop up again 

**Expected behavior**
The tour pop up only triggers once, the first time a user lands on the My Courses dashboard, and the user is able to click okay. 

**Screenshots**
Video:
https://drive.google.com/file/d/1UkJCVUgaQSIuCFGzj_NVn2alo3OlvuWz/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment]
This was fixed by https://github.com/openstax/tutor-js/pull/2715

**Comment by Brooke-Fail** [comment]
This is still happening in QA.

Video:
https://drive.google.com/file/d/1l-PivERTHQy2I2DLDW3iC0HGtDO0KHnT/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Still occurring in QA.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
