### ISSUE TITLE
Bug: Can't edit intro content in exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/tutor#95]
# Scenario 

![Screen Shot 2018-11-12 at 10.50.34 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/c34c2901-eafa-4161-906d-ae37a518b027)

I can't edit the intro? There's no tab on these. I'm assuming it's the intro...

Affected assessment IDs:
16335
16489
16490
16491

# Environment

Production
Exercises
log in: openstax

**Comment by lwtchu** [comment]
ES MUY IMPORTANTE. we need to make edits in december

**Comment by nathanstitt** [comment]
Will change editor to show intro tab if the field isn't blank, and not clear the intro when switching from MPQ to single

**Comment by nathanstitt** [comment]
fixed in https://github.com/openstax/tutor-js/pull/2425

**Comment by Malar-Natarajan** [comment]
Retested in QA. I still do not see the Intro tab (which has values) when converting MPQ to single

**Comment by nathanstitt** [comment]
I'm going to move this as "DONE" unless editors complain about the behavior.

**Comment by gregfitch** [comment]
Verified on QA
